services:
  kglog_backend:
    container_name: kglog_backend_dev
    ports:
      - "8001:8001"
    volumes:
      - ./backend:/app
      - /app/.venv
    command: uv run python manage.py runserver 0.0.0.0:8001

  kglog_frontend:
    container_name: kglog_frontend_dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0 --port 5173

  kglog_postgres:
    container_name: kglog_postgres_dev

  kglog_redis:
    container_name: kglog_redis_dev
