services:
  kglog_backend:
    build:
      context: ./backend/
    env_file:
      - .env
    depends_on:
      - kglog_postgres
      - kglog_redis
    networks:
      - kglog_shared

  kglog_frontend:
    build:
      context: ./frontend/
    depends_on:
      - kglog_backend
    networks:
      - kglog_shared

  kglog_postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: kglog
      POSTGRES_USER: kglog
      POSTGRES_PASSWORD: kglog
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - kglog_shared

  kglog_redis:
    image: redis:7-alpine
    networks:
      - kglog_shared

volumes:
  pgdata:

networks:
  kglog_shared:
    driver: bridge
