"""user table

Revision ID: 2fb9d1a6191b
Revises:
Create Date: 2026-03-24 14:22:48.881212

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2fb9d1a6191b"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("password_hash", sa.String(length=128), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=False),
        sa.Column(
            "gender",
            sa.Enum("MALE", "FEMALE", "OTHER", name="gender"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "body_measurements",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("id_user", sa.Integer(), nullable=False),
        sa.Column("measure_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("height", sa.Float(), nullable=False),
        sa.Column("neck", sa.Float(), nullable=False),
        sa.Column("neck_to_shoulder", sa.Float(), nullable=False),
        sa.Column("sleeve", sa.Float(), nullable=False),
        sa.Column("bust", sa.Float(), nullable=False),
        sa.Column("left_arm", sa.Float(), nullable=False),
        sa.Column("right_arm", sa.Float(), nullable=False),
        sa.Column("waist", sa.Float(), nullable=False),
        sa.Column("hip", sa.Float(), nullable=False),
        sa.Column("inseam_to_ankle", sa.Float(), nullable=False),
        sa.Column("left_leg", sa.Float(), nullable=False),
        sa.Column("right_leg", sa.Float(), nullable=False),
        sa.Column("left_calf", sa.Float(), nullable=False),
        sa.Column("right_calf", sa.Float(), nullable=False),
        sa.Column("shoulders", sa.Float(), nullable=False),
        sa.Column("trunk", sa.Float(), nullable=False),
        sa.Column("pelvis", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_user"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "body_compositions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("id_user", sa.Integer(), nullable=False),
        sa.Column("id_measurements", sa.Integer(), nullable=True),
        sa.Column("measure_date", sa.DateTime(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("fat_percentage", sa.Float(), nullable=False),
        sa.Column("fat_kg", sa.Float(), nullable=False),
        sa.Column("muscle_percentage", sa.Float(), nullable=False),
        sa.Column("muscle_kg", sa.Float(), nullable=False),
        sa.Column("bone_percentage", sa.Float(), nullable=False),
        sa.Column("bone_kg", sa.Float(), nullable=False),
        sa.Column("water_percentage", sa.Float(), nullable=False),
        sa.Column("water_kg", sa.Float(), nullable=False),
        sa.Column("visceral_fat", sa.Float(), nullable=False),
        sa.Column("is_fat_estimated", sa.Boolean(), nullable=False),
        sa.Column("is_muscle_estimated", sa.Boolean(), nullable=False),
        sa.Column("is_bone_estimated", sa.Boolean(), nullable=False),
        sa.Column("is_water_estimated", sa.Boolean(), nullable=False),
        sa.Column("is_visceral_fat_estimated", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_measurements"],
            ["body_measurements.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id_user"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("body_compositions")
    op.drop_table("body_measurements")
    op.drop_table("users")
    # ### end Alembic commands ###
