"""on delete action id_measurements

Revision ID: 48f3ef98a43f
Revises: cd300c87534a
Create Date: 2026-03-24 21:27:47.023748

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "48f3ef98a43f"
down_revision: Union[str, Sequence[str], None] = "cd300c87534a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("body_compositions_id_measurements_fkey"),
        "body_compositions",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "body_compositions",
        "body_measurements",
        ["id_measurements"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "body_compositions", type_="foreignkey")
    op.create_foreign_key(
        op.f("body_compositions_id_measurements_fkey"),
        "body_compositions",
        "body_measurements",
        ["id_measurements"],
        ["id"],
    )
    # ### end Alembic commands ###
