"""on delete actions

Revision ID: cd300c87534a
Revises: 2fb9d1a6191b
Create Date: 2026-03-24 21:21:51.236790

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cd300c87534a"
down_revision: Union[str, Sequence[str], None] = "2fb9d1a6191b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("body_compositions_id_user_fkey"),
        "body_compositions",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "body_compositions",
        "users",
        ["id_user"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("body_measurements_id_user_fkey"),
        "body_measurements",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "body_measurements",
        "users",
        ["id_user"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "body_measurements", type_="foreignkey")
    op.create_foreign_key(
        op.f("body_measurements_id_user_fkey"),
        "body_measurements",
        "users",
        ["id_user"],
        ["id"],
    )
    op.drop_constraint(None, "body_compositions", type_="foreignkey")
    op.create_foreign_key(
        op.f("body_compositions_id_user_fkey"),
        "body_compositions",
        "users",
        ["id_user"],
        ["id"],
    )
    # ### end Alembic commands ###
